name: 'proxy mallory action'
description: 'set proxy on github runner (http proxy over ssh)'
inputs:
  host:  # id of input
    description: 'host'
    required: true
    default: ''
  port:  # id of input
    description: 'port'
    required: true
    default: ''
  user:  # id of input
    description: 'user name'
    required: true
    default: ''
  ssh_key:  # id of input
    description: 'key in base64 format'
    required: true
    default: ''
  proxy_url:
    description: 'Url_a,Url_b'
    required: false
    default: ''

outputs:
  proxy_host: # id of output
    description: 'The host of proxy'
  proxy_port: # port
    description: 'The http port that can be used in github runner. http_porxy=127.0.0.1:port'
  smart_proxy_port:
    description: 'Only urls that in proxy_url will be proxied'
runs:
  using: 'node16'
  main: 'index.js'